/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 18090107
 */
public class dokumen extends javax.swing.JFrame {

    private void kosongkan_from() {
        txtkodedokumen.setEditable(true);
        txtkodedokumen.setText(null);
        txtnamadokumen.setText(null);
        cmbkatagoridokumen.setSelectedItem(this);
        txtlokasi.setText(null);
        txtdeskripsi.setText(null);
        txttanggal.setText(null);
    }
    
    private void tampilkan_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Kode Dokumen");
        model.addColumn("Nama Dokumen");
        model.addColumn("Kategori Dokumen");
        model.addColumn("Lokasi Dokumen");
        model.addColumn("Deskripsi Dokumen");
        model.addColumn("Tanggal");
        
        String cari= txtcari.getText();
        try {
            int no = 1;
            String sql = "SELECT *FROM tb_dokumen WHERE nama LIKE '%"+cari+"%' ";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()) {
                model.addRow(new Object[]{no++,res.getString(1),
                        res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            tabledokumen.setModel(model);
        } catch (Exception e) {
            System.out.println("Error : "+e.getMessage());
        }
    }
    public dokumen() {
        initComponents();
        tampilkan_data();
        kosongkan_from();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtkodedokumen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnamadokumen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlokasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdeskripsi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbkatagoridokumen = new javax.swing.JComboBox<>();
        btnTambahData = new javax.swing.JButton();
        btnSiimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledokumen = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("18090107");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Kode Dokumen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 148, -1));

        txtkodedokumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodedokumenActionPerformed(evt);
            }
        });
        getContentPane().add(txtkodedokumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 102, 312, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Dokumen");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 140, 148, -1));

        txtnamadokumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamadokumenActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamadokumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 142, 312, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Kategori Dokumen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 180, 148, -1));
        getContentPane().add(txtlokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 222, 312, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Lokasi Dokumen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 220, 148, -1));
        getContentPane().add(txtdeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 262, 312, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Deskripsi Dokumen");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 260, 160, -1));
        getContentPane().add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 302, 312, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 300, 148, -1));

        cmbkatagoridokumen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        cmbkatagoridokumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkatagoridokumenActionPerformed(evt);
            }
        });
        getContentPane().add(cmbkatagoridokumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 182, 152, -1));

        btnTambahData.setText("Tambah Data");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 349, -1, -1));

        btnSiimpan.setText("Simpan");
        btnSiimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 349, -1, -1));

        btnHapus.setText("hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 349, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 349, 76, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 349, 66, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 349, -1, -1));

        tabledokumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledokumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledokumenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledokumen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 520, 199));

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 40, -1));

        jLabel10.setFont(new java.awt.Font("Swis721 Blk BT", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("SEARCH");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 510, 30));

        jLabel11.setFont(new java.awt.Font("Swis721 Blk BT", 1, 35)); // NOI18N
        jLabel11.setText("ARSIP DOKUMEN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 510, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apps/wp1836740.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        kosongkan_from();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        try {
            String sql = "INSERT INTO tb_dokumen VALUES ('"+txtkodedokumen.getText()+"','"+txtnamadokumen.getText()+"','"+cmbkatagoridokumen.getSelectedItem()+"','"+txtlokasi.getText()+"','"+txtdeskripsi.getText()+"','"+txttanggal.getText()+"')";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses simpan Data berhasil");
            tampilkan_data();
            kosongkan_from(); 
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        txtkodedokumen.setFocusable(true);
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void btnSiimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiimpanActionPerformed
        try {
            String sql = "INSERT INTO tb_dokumen VALUES ('"+txtkodedokumen.getText()+"','"+txtnamadokumen.getText()+"','"+cmbkatagoridokumen.getSelectedItem()+"','"+txtlokasi.getText()+"','"+txtdeskripsi.getText()+"','"+txttanggal.getText()+"')";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses simpan Data berhasil");
            tampilkan_data();
            kosongkan_from(); 
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }//GEN-LAST:event_btnSiimpanActionPerformed

    private void tabledokumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledokumenMouseClicked
        int baris = tabledokumen.rowAtPoint(evt.getPoint());
        String nik = tabledokumen.getValueAt(baris, 1).toString();
        txtkodedokumen.setText(nik);
        
        String nama = tabledokumen.getValueAt(baris, 2).toString();
        txtnamadokumen.setText(nama);
        
        String jab = tabledokumen.getValueAt(baris, 3).toString();
        cmbkatagoridokumen.setSelectedItem(jab);
        
        String alamat = tabledokumen.getValueAt(baris, 4).toString();
        txtlokasi.setText(alamat);
        
        String email = tabledokumen.getValueAt(baris, 5).toString();
        txtdeskripsi.setText(email);
        
        String telp = tabledokumen.getValueAt(baris, 6).toString();
        txttanggal.setText(telp);
    }//GEN-LAST:event_tabledokumenMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            String sql = "UPDATE tb_dokumen SET kode = '"+txtkodedokumen.getText()+"',nama = '"+txtnamadokumen.getText()+"',kategori = '"+cmbkatagoridokumen.getSelectedItem()+"',lokasi = '"+txtlokasi.getText()+"',deskripsi = '"+txtdeskripsi.getText()+"',tanggal = '"+txttanggal.getText()+"' WHERE kode = '"+txtkodedokumen.getText()+"'";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_from();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            String sql = "DELETE FROM tb_dokumen WHERE kode = '"+txtkodedokumen.getText()+"'";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_from();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        tampilkan_data();
    }//GEN-LAST:event_txtcariKeyPressed

    private void txtnamadokumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamadokumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamadokumenActionPerformed

    private void txtkodedokumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodedokumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodedokumenActionPerformed

    private void cmbkatagoridokumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkatagoridokumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkatagoridokumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dokumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSiimpan;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JComboBox<String> cmbkatagoridokumen;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledokumen;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtdeskripsi;
    private javax.swing.JTextField txtkodedokumen;
    private javax.swing.JTextField txtlokasi;
    private javax.swing.JTextField txtnamadokumen;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
